# This is a basic workflow to help you get started with Actions

name: Deploy to GitHub Pages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  filterBranch:
    name: Filter branch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Filter branch
      uses: actions/bin/filter@main
      with:
        args: branch master
    - name: Install
      uses: actions/npm@main
      with:
        args: install --prefix ./website
    - name: Update version
      uses: clay/docusaurus-github-action@main
      with:
        args: version
    - name: Build and push docs
      uses: clay/docusaurus-github-action@main
      env:
        DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
      with:
        args: deploy
